### ISSUE TITLE
[QUESTION] How to train Traditional YOLO

### ISSUE THREAD

**Issue by benjamingb** [LdDl/rust-road-traffic#27]
Hi
How do you train models for Darknet?
I've been training it on Ultralytics and converted it to ONNX, but the model is very heavy and also consumes more CPU. Darknet models seem to be lighter, but I haven't found a way to train a custom model. How do you do it?

**Comment by LdDl** [comment]
Hi
I'm using this README - https://github.com/AlexeyAB/darknet?tab=readme-ov-file#how-to-train-to-detect-your-custom-objects

It is pretty good for both novice and advanced user. But be prepared to face installation steps also.
You could use Pytorch version with further ONNX conversion, but I've never used it - https://github.com/Tianxiaomo/pytorch-YOLOv4/blob/master/train.py
